import scrapy

from sueldos.items import SueldosItem

class GetOnBoardSpider(scrapy.Spider):
    name = "getonboard"
    allowed_domains = ["getonbrd.cl"]
    start_urls = [
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-classroom-tv",
    "https://www.getonbrd.cl/empleos/programacion/aquitecto-de-software-ingenieria-latitud-33",
    "https://www.getonbrd.cl/empleos/programacion/aquitecto-de-software-ingenieria-latitud-33",
    "https://www.getonbrd.cl/empleos/programacion/backend-developer-arquitect-ned",
    "https://www.getonbrd.cl/empleos/programacion/backend-developer-avalancha",
    "https://www.getonbrd.cl/empleos/programacion/backend-developer-leadsius",
    "https://www.getonbrd.cl/empleos/programacion/backend-developer-ned",
    "https://www.getonbrd.cl/empleos/programacion/back-end-developer-smartboxtv-1824",
    "https://www.getonbrd.cl/empleos/programacion/backend-developer-tech-k-869e",
    "https://www.getonbrd.cl/empleos/programacion/conspultor-middleware-adep-imagemaker",
    "https://www.getonbrd.cl/empleos/programacion/data-base-administrator-tech-k",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-4talent",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-android-case-surfer",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-backend-analitic",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-back-end-boosmap",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-backend-concepto-group",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-back-end-senior-zyght",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-back-end-tsolutions",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-csw-consultores-ambientales",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-django-magnet",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-django-ipartner",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-eclass-8b5f",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-nursoft-5c3f",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-option",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-rankmi",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-front-end-reactoragencia-digital",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-full-stack-dentalink",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-full-stack-engie-factory-b3a1",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-fullstack-rankmi",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-full-stack-taag-genetics",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-js-react-zbox",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-kunder",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-mas-energia-ltda",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-og-services-s-a",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-postcenter",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-practicante-jr-green-teknik",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-python-backend-rutapro",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-ror-oferus",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-ror-oferus-191e",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-ruby-on-rais-cloudintelligence-spa",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-ruby-ror-upsocl",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-senior-aqmarket",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-senior-beetrack",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-senior-beetrack-a44b",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-soa-oracle-osb-imagemaker",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-waya",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-web-dalepega",
    "https://www.getonbrd.cl/empleos/programacion/desarrollador-web-fundacion-ciudadano-inteligente",
    "https://www.getonbrd.cl/empleos/programacion/developer-senior-classroomtv-com",
    "https://www.getonbrd.cl/empleos/programacion/engineering-manager-able",
    "https://www.getonbrd.cl/empleos/programacion/engine-gameplay-programmer-ace-team",
    "https://www.getonbrd.cl/empleos/programacion/front-end-developer-portaloficina-com",
    "https://www.getonbrd.cl/empleos/programacion/front-end-developer-smartboxtv",
    "https://www.getonbrd.cl/empleos/programacion/front-end-digital-meat",
    "https://www.getonbrd.cl/empleos/programacion/frontend-maqueteador-html-fusiona",
    "https://www.getonbrd.cl/empleos/programacion/front-end-webdox",
    "https://www.getonbrd.cl/empleos/programacion/full-stack-developer-osa",
    "https://www.getonbrd.cl/empleos/programacion/full-stack-developer-tech-k-3b90",
    "https://www.getonbrd.cl/empleos/programacion/full-stack-developer-web-anchor",
    "https://www.getonbrd.cl/empleos/programacion/full-stack-engineer-with-an-ad-nisum-technologies",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-a-civil-computacion-platanus",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-desarrollo-django-we-technologies",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-desarrollador-front-imagemaker",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-desarrollador-routinguc",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-desarrollo-de-softwa-redd-system",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-desarrollo-junior-switch-comunicaciones-ltda-ec90",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-classroom-tv",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-componente-serviex-ab46",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-desert-point",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-karibu-ltda",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-de-software-senior-latam-airlines-group",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-en-desarrollo-nodejs-optimiza-chile",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-en-vision-artificial-biometrypass",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-front-end-puntoticket",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-informatico-cakephp-idea-uno-ltda",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-java-pl-sql-imagemaker",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-software-junior-java-23people",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-ti-innovador-myhotel-spa",
    "https://www.getonbrd.cl/empleos/programacion/ingeniero-web-java-imagemaker",
    "https://www.getonbrd.cl/empleos/programacion/lead-developer-bananadesk",
    "https://www.getonbrd.cl/empleos/programacion/programador-de-backend-tinybytes",
    "https://www.getonbrd.cl/empleos/programacion/programador-de-videojuegos-tinybytes",
    "https://www.getonbrd.cl/empleos/programacion/programador-devops-poc",
    "https://www.getonbrd.cl/empleos/programacion/programador-en-practica-rocketpin",
    "https://www.getonbrd.cl/empleos/programacion/programador-expan",
    "https://www.getonbrd.cl/empleos/programacion/programador-full-stack-greenti",
    "https://www.getonbrd.cl/empleos/programacion/programador-gatek",
    "https://www.getonbrd.cl/empleos/programacion/programador-javascript-venture-capital",
    "https://www.getonbrd.cl/empleos/programacion/programador-junior-o-senior-ready-computing-spa",
    "https://www.getonbrd.cl/empleos/programacion/programador-php-exportadora-prize",
    "https://www.getonbrd.cl/empleos/programacion/programador-tcit",
    "https://www.getonbrd.cl/empleos/programacion/python-engineer-cornershop-inc",
    "https://www.getonbrd.cl/empleos/programacion/ror-backend-frontend-webdox",
    "https://www.getonbrd.cl/empleos/programacion/ruby-on-rails-expert-pasajebus-com",
    "https://www.getonbrd.cl/empleos/programacion/senior-ror-developer",
    "https://www.getonbrd.cl/empleos/programacion/senior-software-engineer-admetricks-com",
    "https://www.getonbrd.cl/empleos/programacion/senior-software-engineer-georgio-bruzzo-gmail-com-bfc4",
    "https://www.getonbrd.cl/empleos/programacion/softwareengineer-mercado-libre-ventus-partner",
    "https://www.getonbrd.cl/empleos/programacion/web-developer-backend-fosubo",
    "https://www.getonbrd.cl/empleos/programacion/web-developer-ned"
    ]

    def parse(self, response):
        item = SueldosItem()
        item['tecnologia'] = response.xpath('//div[@class="col-md-6"]//span[@class="tag"]/a').re(r'>\s*(.*)')
        item['sueldo'] = response.xpath('//div[@class="col-md-6"]//strong').re(r'>\s*(.*)')
        item['nombre_empresa'] = response.xpath('//div[@class="company-profile"]//h3//span[@itemprop="hiringOrganization"]').re(r'>\s*(.*)')
        yield item
